### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by escalepion** [escalepion/movies#1]
Task List

**Comment by escalepion** [comment]
- [x] Add user informations. Name, username etc. 

- [x] User name in right side bar

- [x] Add "no movies or tv series" if the section doesnt have  any item

- [ ] User profil pic upload
